// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CourseContract$Type } from "./CourseContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CourseContract"]: CourseContract$Type;
    ["contracts/Course.sol:CourseContract"]: CourseContract$Type;
  }

  interface ContractTypesMap {
    ["CourseContract"]: GetContractReturnType<CourseContract$Type["abi"]>;
    ["contracts/Course.sol:CourseContract"]: GetContractReturnType<CourseContract$Type["abi"]>;
  }
}
